name: monorepo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci --prefix docs/docs-site
      - run: npm run build --prefix docs/docs-site

  build-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci --prefix website
      - run: npm run build --prefix website

  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r tools/tooling/requirements.txt
      - run: flake8 tools/tooling
      - run: black --check tools/tooling

  test-tooling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r tools/tooling/requirements.txt
      - run: pytest tools/tooling/tests/

  validate-specs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r tools/tooling/requirements.txt
      - name: Validate vendor registry
        run: |
          for f in registry/vendor-registry/vendors/*.json; do
            python -m openauthcert_tooling.validate_vendor "$f" || exit 1
          done
      - name: Validate badge specs
        run: |
          for f in specs/badge-spec/specs/**/*.json; do
            python -m openauthcert_tooling.validate_badge "$f" || exit 1
          done

