name: revoke-on-fail

on:
  workflow_dispatch:
    inputs:
      badge_path:
        description: 'Path to badge JSON to revoke (e.g. registry/badge-registry/vendor_app_version.json)'
        required: true
      notes:
        description: 'Reason for revocation'
        required: false

permissions:
  contents: write
  pull-requests: write

jobs:
  revoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install tooling dependencies
        run: pip install -r tools/tooling/requirements.txt
      - name: Update badge metadata
        env:
          BADGE_PATH: ${{ github.event.inputs.badge_path }}
          NOTES: ${{ github.event.inputs.notes }}
        run: |
          python - <<'PY'
import datetime as dt
import json
import os
from pathlib import Path

badge_path = Path(os.environ['BADGE_PATH'])
badge = json.loads(badge_path.read_text())
badge['status'] = 'revoked'
badge['revoked_at'] = dt.datetime.utcnow().isoformat() + 'Z'
notes = os.environ.get('NOTES')
if notes:
    badge['notes'] = notes
badge.pop('digital_signature', None)
badge_path.write_text(json.dumps(badge, indent=2, sort_keys=True) + '\n')
PY
      - name: Write private key material
        run: |
          echo "${{ secrets.OAC_PRIVATE_KEY_B64 }}" > /tmp/oac_private.b64
      - name: Re-sign badge
        env:
          BADGE_PATH: ${{ github.event.inputs.badge_path }}
        run: |
          python tools/tooling/sign_verify.py sign "$BADGE_PATH" /tmp/oac_private.b64
      - name: Commit and push revocation
        env:
          BADGE_PATH: ${{ github.event.inputs.badge_path }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add "$BADGE_PATH"
          git commit -m "Revoke badge $BADGE_PATH"
          git push
