name: validate-badges

on:
  pull_request:
    paths:
      - 'registry/**'
      - 'specs/badge-spec/**'
      - 'tools/tooling/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install tooling dependencies
        run: pip install -r tools/tooling/requirements.txt
      - name: Validate badge registry
        run: python tools/tooling/validate_badges.py registry/badge-registry specs/badge-spec/schema-v1.json specs/badge-spec/public.pem
